### ISSUE TITLE
[BUG🐛] Compatibility Issues with TTS().from_pretrained() and Configurations for XTTSv2

### ISSUE THREAD

**Issue by elvinzade** [astramind-ai/Auralis#17]
## Bug Report: Compatibility Issues with TTS().from_pretrained() and Configurations for XTTSv2
Description
I encountered multiple issues when attempting to use the TTS().from_pretrained() function with a fine-tuned XTTSv2 model converted to safetensors. Below are the details:

## Steps to Reproduce
Convert the fine-tuned .pth model to safetensors using checkpoint_converter.py.
Attempt to create a TTS instance using:

tts = TTS().from_pretrained("path/core-xttsv2_model", gpt_model='path/xttsv2-gpt_model')
Encounter the following error:

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace[/repo_name]'
Attempt to handle the issue by manually loading the config.json file.
## Observations
The config.json file in the original XTTSv2 model is not compatible with the config.json in AstraMindAI/xttsv2.
After using the config.json from AstraMindAI/xttsv2, another error occurs:

[rank0]: During handling of the above exception, another exception occurred:
[rank0]: Traceback (most recent call last):
[rank0]:   File "inference_auralis.py", line 4, in <module>
[rank0]:     tts = TTS().from_pretrained("path/core_xttsv2", gpt_model='path/gpt')
[rank0]:   File "python3.10/site-packages/auralis/core/tts.py", line 61, in from_pretrained
[rank0]:     raise ValueError(f"Could not load model from {model_name_or_path}: {e}")
[rank0]: ValueError: Could not load model from path/core_xttsv2: Error(s) in loading state_dict for XTTSv2Engine:
Expected Behavior
The fine-tuned model, converted to safetensors, should be compatible with from_pretrained() without needing significant manual adjustments to config.json.

## Additional Information
Environment:
Python version: 3.10
OS: [ Ubuntu 20.04]
Steps Taken to Resolve:
Attempted to handle the issue by using AstraMindAI/xttsv2 config.json.
Result: Same error persists.
## Request
Could you confirm compatibility between the config.json files of the original XTTSv2 model and AstraMindAI/xttsv2?
Is there a standardized process for converting .pth models to safetensors while maintaining compatibility?
Suggestions for resolving the state dictionary errors?

**Comment by u1vi** [comment]
I have same problem

**Comment by mmikayilaliyev** [comment]
I also got same problem!

**Comment by saifulislam79** [comment]
Same issue here,

Traceback (most recent call last):
  File "/opt/conda/envs/astramind_v2/lib/python3.10/site-packages/auralis/core/tts.py", line 46, in from_pretrained
    config_path = hf_hub_download(repo_id=model_name_or_path, filename='config.json')
  File "/opt/conda/envs/astramind_v2/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/envs/astramind_v2/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/sayan/Auralis/src/auralis/models/xttsv2/utils/converted_model_v2/core_xttsv2'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sayan/Auralis/inference.py", line 6, in <module>
    tts = TTS().from_pretrained(
  File "/opt/conda/envs/astramind_v2/lib/python3.10/site-packages/auralis/core/tts.py", line 54, in from_pretrained
    raise ValueError(f"Could not load model from {model_name_or_path}: {e}")
ValueError: Could not load model from /home/sayan/Auralis/src/auralis/models/xttsv2/utils/converted_model_v2/core_xttsv2: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/sayan/Auralis/src/auralis/models/xttsv2/utils/converted_model_v2/core_xttsv2'. Use `repo_type` argument if needed.
