### ISSUE TITLE
[BUG🐛] Title: Tokenizer Update Issue After Fine-Tuning Model for a New Language

### ISSUE THREAD

**Issue by elvinzade** [astramind-ai/Auralis#29]
## Description:
I fine-tuned the XTTSV2 model for a new language. In order to use your solution i follow all instructions you provided. However, updating the tokenizer.json and tokenizer_config.json to include the new tokens has caused issues with the model.

## Mismatch Error:
After appending new tokens to the existing vocabulary, the total number of tokens increased (from 6681 to 8155). This caused a mismatch error because the model's input embeddings are not resized to match the updated tokenizer's vocabulary size.
## OOV Error:
When I attempted to delete tokens from the language in the tokenizer vocabulary to manage the vocabulary size, I encountered the following error:

fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: Token `сво` out of vocabulary at line 32901 column 1

**Comment by mlinmg** [comment]
There shouldn't be any problems with the loading of a custom tokenizer as long as it is properly configured. Are you trying to add a new with non standard characters? You could try using the spaCy library, as used in the Tokenizer class in xTTSv2, to convert non-Latin characters to Latin(so you will not add any tokens to the dictionary) . Anyway this seems to net be an issue with Auralis but rather with xtts training, so i'm closing this issue for now, feel free to reopen if you think it's not the case
