### ISSUE TITLE
[BUG🐛] TTS.configure() is not implemented! 

### ISSUE THREAD

**Issue by JahidBasher** [astramind-ai/Auralis#49]
## Bug Description
tts.configure() is not available as mentioned in docs/advanced/performance-tuning.md. Is the doc part of an older codebase?

## Minimal Reproducible Example

```python
from auralis import TTS
from auralis.common.logging import setup_logger

# Enable debug logging to monitor performance
logger = setup_logger(__name__, level="DEBUG")

# Initialize with VLLM
tts = TTS(use_vllm=True)

tts.configure(
    batch_size=4,  # Adjust based on VRAM
    use_kv_cache=True,
    max_batch_size=8,
    gpu_memory_utilization=0.95
)
```

**Comment by mlinmg** [comment]
it is an addition that will be probably implemented in the next version of Auralis, when the refactoring is completed for now it's not present. You now have control on the max scheduler concurrency
